Fix: Extension should show offline in status bar without notification
pullflow/vscode-pullflow pull request #3
Opened 2023-10-26 14:39 UTC by hassan-pullflow

### Summary of Changes 

- added `warning icon ⚠️` for offline status
- removed notifications for offline status error
- updated reconnect command to run `activePullRequest` command when user clicks status bar

### PR-Specific Tests

- User signs in on extension > User see pull requests on status bar > User turns off internet > User sees warning icon next to Pullflow icon > User turns on internet > User clicks status bar > User sees updated pull requests on quick pick.

2023-10-30 21:13 UTC, amna-pullflow requested changes
please add screenshots for UI changes

2023-10-30 21:13 UTC, amna-pullflow commented on src/views/statusBar/statusBar.ts
> +    return `${presenceIcon} ${pendingCodeReviewsCount} ${errorIcon} $(pullflow-icon) ${authoredCodeReviewsCount}`
```suggestion
    return `${errorIcon} ${presenceIcon} ${pendingCodeReviewsCount} $(pullflow-icon) ${authoredCodeReviewsCount}`
```

2023-10-31 17:19 UTC, srzainab requested changes
We want to keep the same order for the icons.

2023-10-31 17:19 UTC, srzainab commented on src/views/statusBar/statusBar.ts
> +    return `${presenceIcon} ${errorIcon} $(pullflow-icon)`
```suggestion
    return `${errorIcon} ${presenceIcon} $(pullflow-icon)`
```

2023-10-31 20:07 UTC, amna-pullflow approved these changes

2023-10-31 20:57 UTC, srzainab approved these changes

2023-10-31 21:03 UTC, merged